# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0007_auto_20161101_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='JSON response')),
                ('date', models.DateTimeField(verbose_name='Date taken')),
                ('inactive_seconds', models.CharField(max_length=50)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
    ]
