# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='date',
        ),
        migrations.RemoveField(
            model_name='response',
            name='inactive_seconds',
        ),
    ]
