# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take', '0003_response_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='inactive_ms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
