# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take', '0005_response_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='ungraded_questions',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
