# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='JSON response')),
                ('date', models.DateTimeField(verbose_name='Date taken')),
                ('inactive_seconds', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown', models.TextField(null=True, verbose_name='Kale code')),
                ('html', models.TextField(null=True, verbose_name='HTML test')),
                ('answers', models.TextField(null=True, verbose_name='JSON answers')),
                ('security', models.BooleanField()),
                ('allow_question_review', models.BooleanField()),
                ('date', models.DateTimeField(verbose_name='Date created')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('access_code', models.CharField(max_length=6, null=True, verbose_name='Class access codes')),
                ('archived', models.BooleanField()),
                ('deleted', models.BooleanField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='paper',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.AddField(
            model_name='response',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Test'),
        ),
    ]
