# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answers',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='html',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='markdown',
            field=models.TextField(null=True),
        ),
    ]
