# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161030_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='access_code',
            field=models.CharField(max_length=50, null=True, verbose_name='Class access codes'),
        ),
    ]
