# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161031_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
