# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161031_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='test',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
